training_demos:
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo1/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo1'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo2/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo2'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo3/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo3'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo5/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo5'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo6/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo6'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo7/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo7'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo8/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo8'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo9/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo9'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo10/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo10'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo11/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo11'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo12/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo12'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo13/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo13'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo14/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo14'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo15/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo15'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo16/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo16'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo17/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo17'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo18/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo18'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo19/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo19'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo20/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo20'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo21/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo21'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo22/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo22'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo23/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo23'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo24/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo24'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo26/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo26'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo27/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo27'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo28/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo28'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo29/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo29'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo30/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo30'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo31/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo31'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo33/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo33'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo34/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo34'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo35/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo35'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo36/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo36'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo37/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo37'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo38/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo38'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo39/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo39'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo40/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo40'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo41/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo41'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo42/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo42'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo43/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo43'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo44/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo44'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo45/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo45'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo46/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo46'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo47/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo47'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo48/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo48'

validation_demos:
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo32/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo32'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo25/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo25'
  - dataset_csv: '/home/joeya/pick_and_place_dataset/demo4/dataset.csv'
    image_dir: '/home/joeya/pick_and_place_dataset/demo4'