demos:
  - dataset_csv: '/home/joeya/dataset/demo1/dataset.csv'
    image_dir: '/home/joeya/dataset/demo1'
  - dataset_csv: '/home/joeya/dataset/demo2/dataset.csv'
    image_dir: '/home/joeya/dataset/demo2'
  - dataset_csv: '/home/joeya/dataset/demo3/dataset.csv'
    image_dir: '/home/joeya/dataset/demo3'
  - dataset_csv: '/home/joeya/dataset/demo4/dataset.csv'
    image_dir: '/home/joeya/dataset/demo4'
  - dataset_csv: '/home/joeya/dataset/demo5/dataset.csv'
    image_dir: '/home/joeya/dataset/demo5'
  - dataset_csv: '/home/joeya/dataset/demo6/dataset.csv'
    image_dir: '/home/joeya/dataset/demo6'
  - dataset_csv: '/home/joeya/dataset/demo7/dataset.csv'
    image_dir: '/home/joeya/dataset/demo7'
  - dataset_csv: '/home/joeya/dataset/demo8/dataset.csv'
    image_dir: '/home/joeya/dataset/demo8'
  - dataset_csv: '/home/joeya/dataset/demo9/dataset.csv'
    image_dir: '/home/joeya/dataset/demo9'
  - dataset_csv: '/home/joeya/dataset/demo10/dataset.csv'
    image_dir: '/home/joeya/dataset/demo10'
  - dataset_csv: '/home/joeya/dataset/demo11/dataset.csv'
    image_dir: '/home/joeya/dataset/demo11'
  - dataset_csv: '/home/joeya/dataset/demo12/dataset.csv'
    image_dir: '/home/joeya/dataset/demo12'
  - dataset_csv: '/home/joeya/dataset/demo13/dataset.csv'
    image_dir: '/home/joeya/dataset/demo13'
  - dataset_csv: '/home/joeya/dataset/demo14/dataset.csv'
    image_dir: '/home/joeya/dataset/demo14'
  - dataset_csv: '/home/joeya/dataset/demo15/dataset.csv'
    image_dir: '/home/joeya/dataset/demo15'
  - dataset_csv: '/home/joeya/dataset/demo16/dataset.csv'
    image_dir: '/home/joeya/dataset/demo16'
  - dataset_csv: '/home/joeya/dataset/demo17/dataset.csv'
    image_dir: '/home/joeya/dataset/demo17'
  - dataset_csv: '/home/joeya/dataset/demo18/dataset.csv'
    image_dir: '/home/joeya/dataset/demo18'
  - dataset_csv: '/home/joeya/dataset/demo19/dataset.csv'
    image_dir: '/home/joeya/dataset/demo19'
  # - dataset_csv: '/home/joeya/dataset/demo20/dataset.csv'
  #   image_dir: '/home/joeya/dataset/demo20'