demos:
  - dataset_csv: '/home/joeya/dataset/demo1/dataset.csv'
    targets_csv: '/home/joeya/dataset/demo1/targets.csv'
    image_dir: '/home/joeya/dataset/demo1'
  - dataset_csv: '/home/joeya/dataset/demo2/dataset.csv'
    targets_csv: '/home/joeya/dataset/demo2/targets.csv'
    image_dir: '/home/joeya/dataset/demo2'
  - dataset_csv: '/home/joeya/dataset/demo3/dataset.csv'
    targets_csv: '/home/joeya/dataset/demo3/targets.csv'
    image_dir: '/home/joeya/dataset/demo3'
  - dataset_csv: '/home/joeya/dataset/demo4/dataset.csv'
    targets_csv: '/home/joeya/dataset/demo4/targets.csv'
    image_dir: '/home/joeya/dataset/demo4'
  - dataset_csv: '/home/joeya/dataset/demo5/dataset.csv'
    targets_csv: '/home/joeya/dataset/demo5/targets.csv'
    image_dir: '/home/joeya/dataset/demo5'
  - dataset_csv: '/home/joeya/dataset/demo6/dataset.csv'
    targets_csv: '/home/joeya/dataset/demo6/targets.csv'
    image_dir: '/home/joeya/dataset/demo6'
  - dataset_csv: '/home/joeya/dataset/demo7/dataset.csv'
    targets_csv: '/home/joeya/dataset/demo7/targets.csv'
    image_dir: '/home/joeya/dataset/demo7'
  - dataset_csv: '/home/joeya/dataset/demo8/dataset.csv'
    targets_csv: '/home/joeya/dataset/demo8/targets.csv'
    image_dir: '/home/joeya/dataset/demo8'
  - dataset_csv: '/home/joeya/dataset/demo9/dataset.csv'
    targets_csv: '/home/joeya/dataset/demo9/targets.csv'
    image_dir: '/home/joeya/dataset/demo9'
  - dataset_csv: '/home/joeya/dataset/demo10/dataset.csv'
    targets_csv: '/home/joeya/dataset/demo10/targets.csv'
    image_dir: '/home/joeya/dataset/demo10'